doctrine:
 dbal:
   types:
     uuid:  Ramsey\Uuid\Doctrine\UuidType

 orm:
   resolve_target_entities:
     Kiboko\Bundle\DMSBundle\Model\AuthorizationInterface: Kiboko\Bundle\DMSBundle\Entity\Authorization
     Kiboko\Bundle\DMSBundle\Model\DocumentInterface: Kiboko\Bundle\DMSBundle\Entity\Document
     Kiboko\Bundle\DMSBundle\Model\DocumentNodeInterface: Kiboko\Bundle\DMSBundle\Entity\DocumentNode
     Kiboko\Bundle\DMSBundle\Model\MetaInterface: Kiboko\Bundle\DMSBundle\Entity\Meta
