navigation:
    menu_config:
        items:
            kiboko_dms_tab:
                label: Documents
                uri:   '#'
                attributes:
                    class: 'mobile-hide'
                position: 300
                extras:
                    icon: fa-image
            kiboko_dms_browse:
                label: Browse
                route: kiboko_dms_index
        tree:
            application_menu:
                children:
                    kiboko_dms_tab:
                        children:
                            kiboko_dms_browse: ~

    titles:
        acme_link: My link page title
