services:
  kiboko_dam.controller.document_node_tree_ajax_controller:
    class: Kiboko\Bundle\DAMBundle\Controller\DocumentNodeTreeAjaxController
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@oro_locale.helper.localization'
      - '@kiboko_dam.tree.document_node_update_tree_handler'

    calls:
      - [setContainer, ["@service_container"]]

  kiboko_dam.controller.asset_widget:
    class: Kiboko\Bundle\DAMBundle\Controller\AssetWidgetController
    arguments:
      - '@kiboko_dam.form.document.widget.upload_asset'
      - '@oro_form.update_handler'
      - '@translator'
      - '@oro_action.helper.context'
      - '@doctrine.orm.entity_manager'
      - %kernel.project_dir%

  kiboko_dam.controller.document:
    class: Kiboko\Bundle\DAMBundle\Controller\DocumentController
    arguments:
      - '@kiboko_dam.form.document'
      - '@oro_form.update_handler'
      - '@translator'
      - '@kiboko_dam.form.handler.document'
      - '@oro_ui.router'
      - '@session'
